# Use the production image as base image
FROM task-app_api
# Copy the test files
COPY test test
# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev
# 1. Get test packages; AND
# 2. Install our test framework - mocha
RUN npm update
# Override the command, to run the test instead of the application
CMD ["npm", "run", "test"]